<?php


namespace MMunoz;


class World extends APIObject
{
    public $players_online_data;

    public $name;
    public $players_online;
    public $online_record;
    public $creation_date;
    public $location;
    public $pvp_type;
    public $world_quest_titles;
    public $battleye_status;

    public function setData($data)
    {
        $this->players_online_data = $data['players_online'];
        return parent::setData($data['world_information']); // TODO: Change the autogenerated stub
    }


}